name: Build release
on:
  release:
    types: [created]

permissions:
  contents: write
  id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22'

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::028537455170:role/Github/GithubAssetsUploadRole_guides-converter-v3
          role-session-name: GithubAction


      - name: Copy files S3
        run: |
          aws s3 cp dist/binary/ s3://codio-assets/guides-converter-v3/ --recursive --cache-control no-cache

      - name: Copy files S3 with hash commit
        run: |
          aws s3 cp dist/binary/linux-amd64/guides-converter-v3 s3://codio-assets/guides-converter-v3/guides-converter-v3-"$GITHUB_SHA"
