name: Publish Guides converter V3
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.18'

    - name: make dist
      run: mkdir dist

    - name: build
      run: ./build.sh "$GITHUB_SHA" "dist"
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}

    - name: upload to s3
      run: ./uploadToS3.sh "${{ secrets.ASSETS_UPLOADER_KEY }}" "${{ secrets.ASSETS_UPLOADER_SECRET }}"

    - name: Slack
      uses: codio/codio-slack-action@master
      if: always()
      with:
        slack_hook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        message: "<https://github.com/${{ github.repository }}/actions/runs/${{github.run_id}}|${{ github.workflow }} release> for ${{ github.repository }} by ${{ github.actor }} has ${{ job.status }} on branch ${{ github.ref_name }}"
        success: ${{ job.status }}
